[package]
name = "eclipsecon-demo"
version = "0.1.0"
edition = "2018"
resolver = "2"
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Jens Reimann <jreimann@redhat.com>"
]

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/main.rs"

[dependencies]
embassy = {git = "https://github.com/embassy-rs/embassy.git", rev = "4b74e8fc50b3b1839f118d9b310f793a46adc416", default-features = false }
drogue-device = { git = "https://github.com/drogue-iot/drogue-device", rev = "e3daa54d71f71f952bc358faf6afa6170e72b00b", features = ["fonts", "log"], default-features = false }
#drogue-device = { path = "../drogue-iot/drogue-device/device", features = ["fonts", "log"], default-features = false }
log = "0.4"
embedded-hal = { version = "0.2.4", features = ["unproven"] }
cfg-if = "1.0.0"

# WASM dependencies
wasm-bindgen = { version = "0.2.74", optional = true }
js-sys = { version = "0.3", optional = true }
wasm-bindgen-futures = { version = "0.4.24", optional = true }
wasm-logger = { version = "0.2.0", optional = true }
web-sys = { version = "0.3.4", features = ['Document', 'Element', 'HtmlElement', 'Node', 'Window'], optional = true }
critical-section = { version = "0.2.1", features = ["custom-impl"], optional = true }

# microbit dependencies
embassy-nrf = {git = "https://github.com/embassy-rs/embassy.git", rev = "4b74e8fc50b3b1839f118d9b310f793a46adc416", default-features = false, features = ["nrf52833"], optional = true }
cortex-m-rt = { version = "0.6.13", optional = true }
#cortex-m = { version = "0.7.1", features = ["inline-asm"], optional = true }
panic-probe = { version = "0.2.0", features = ["print-rtt"], optional = true }
rtt-logger = { version = "0.1", optional = true }
rtt-target = { version = "0.2.0", features = ["cortex-m"], optional = true }

[features]
wasm = ["embassy/executor-agnostic", "wasm-bindgen", "js-sys", "wasm-bindgen-futures", "wasm-logger", "web-sys", "critical-section"]
microbit = ["embassy-nrf",
    #"cortex-m", 
    "cortex-m-rt",
        "panic-probe", "rtt-logger", "rtt-target"]
