[package]
name = "eclipsecon-demo"
version = "0.1.0"
edition = "2018"
resolver = "2"
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Jens Reimann <jreimann@redhat.com>"
]

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/main.rs"

[dependencies]
embassy = {git = "https://github.com/embassy-rs/embassy.git", rev = "548593ea415c79472bd2cf2d0c59aadfcf5f715c", default-features = false }
drogue-device = { git = "https://github.com/drogue-iot/drogue-device", rev = "cbf3f40e94edb6be252b9846dca02e95da45b7f8", features = ["fonts", "log"], default-features = false }
log = "0.4"
embedded-hal = { version = "0.2.4", features = ["unproven"] }
cfg-if = "1.0.0"

# WASM dependencies
wasm-bindgen = { version = "=0.2.75", optional = true }
wasm-bindgen-futures = { version = "0.4.24", optional = true }
wasm-logger = { version = "0.2.0", optional = true }
drogue-wasm = { git = "https://github.com/drogue-iot/drogue-wasm", branch = "main", default-features = false, optional = true }

# microbit dependencies
embassy-nrf = {git = "https://github.com/embassy-rs/embassy.git", rev = "548593ea415c79472bd2cf2d0c59aadfcf5f715c", default-features = false, features = ["nrf52833", "gpiote"], optional = true }
cortex-m-rt = { version = "0.7", optional = true }
#cortex-m = { version = "0.7.1", features = ["inline-asm"], optional = true }
panic-probe = { version = "0.2.0", features = ["print-rtt"], optional = true }
rtt-logger = { version = "0.1", optional = true }
rtt-target = { version = "0.2.0", features = ["cortex-m"], optional = true }

[features]
wasm = ["embassy/executor-agnostic", "wasm-bindgen", "wasm-bindgen-futures", "wasm-logger", "drogue-wasm"]
microbit = ["embassy-nrf", "cortex-m-rt", "panic-probe", "rtt-logger", "rtt-target"]
